#!/usr/bin/env python3
"""Regenerate the plugin table in README.md from .claude-plugin/marketplace.json.

The table is the single source of truth's *rendering*; marketplace.json is the
source of truth. Run this after adding or editing a plugin:

    python3 scripts/gen_readme.py

Exits non-zero if the README is out of date is NOT checked here; this just
rewrites. To verify in CI, run it and `git diff --exit-code README.md`.
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MARKETPLACE = ROOT / ".claude-plugin" / "marketplace.json"
README = ROOT / "README.md"

BEGIN = "<!-- BEGIN PLUGINS (autogenerated by scripts/gen_readme.py) -->"
END = "<!-- END PLUGINS -->"


def build_table(plugins):
    rows = ["| Plugin | Description |", "|--------|-------------|"]
    for p in sorted(plugins, key=lambda p: p["name"]):
        name = p["name"]
        desc = " ".join(p["description"].split()).replace("|", "\\|")
        rows.append(f"| `{name}` | {desc} |")
    return "\n".join(rows)


def main():
    data = json.loads(MARKETPLACE.read_text())
    plugins = data["plugins"]
    block = f"{BEGIN}\n\n{build_table(plugins)}\n\n{END}"

    readme = README.read_text()
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    if not pattern.search(readme):
        sys.exit(f"markers not found in {README} (expected {BEGIN} ... {END})")
    README.write_text(pattern.sub(lambda _: block, readme))
    print(f"Wrote {len(plugins)} plugins to {README.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
